/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("prompts").del();
  await knex("prompts").insert([
    {
      id: 1,
      user_id: 1,
      promptseq_id: 1,
      content: "This is some of my favourite poetry. Pay attention to its formal, sensory and aesthetic qualities. \n",
      label: "Preamble",
      order: 1,
    },
    {
      id: 2,
      user_id: 1,
      promptseq_id: 1,
      content: "In a Station of the Metro \n The apparition of these faces in the crowd: \n Petals on a wet, black bough.",
      label: "Pound",
      order: 2,
    },
    {
      id: 3,
      user_id: 1,
      promptseq_id: 1,
      content: "Ozymandias \n I met a traveller from an antique land, \n Who said – 'Two vast and trunkless legs of stone \n Stand in the desert. . . . Near them, on the sand, \n Half sunk a shattered visage lies, whose frown, \n And wrinkled lip, and sneer of cold command, \n Tell that its sculptor well those passions read \n Which yet survive, stamped on these lifeless things, \n The hand that mocked them, and the heart that fed; \n And on the pedestal, these words appear: \n My name is Ozymandias, King of Kings; \n Look on my Works, ye Mighty, and despair! \n Nothing beside remains. Round the decay \n Of that colossal Wreck, boundless and bare \n The lone and level sands stretch far away.'",
      label: "Shelley",
      order: 3,
    },
    {
      id: 4,
      user_id: 1,
      promptseq_id: 1,
      content: "'Hope' is the thing with feathers \n 'Hope' is the thing with feathers - \n That perches in the soul - \n And sings the tune without the words - \n And never stops - at all - \n And sweetest - in the Gale - is heard - \n And sore must be the storm - \n That could abash the little Bird \n That kept so many warm - \n I've heard it in the chillest land - \n And on the strangest Sea - \n Yet - never - in Extremity, \n It asked a crumb - of me.",
      label: "Dickinson",
      order: 4,
    },
    {
      id: 5,
      user_id: 1,
      promptseq_id: 1,
      content: "Let me not to the marriage of true minds \n Admit impediments. Love is not love \n Which alters when it alteration finds, \n Or bends with the remover to remove: \n O no! it is an ever-fixed mark \n That looks on tempests and is never shaken; \n It is the star to every wandering bark, \n Whose worth's unknown, although his height be taken. \n Love's not Time's fool, though rosy lips and cheeks \n Within his bending sickle's compass come: \n Love alters not with his brief hours and weeks, \n But bears it out even to the edge of doom. \n If this be error and upon me proved, \n I never writ, nor no man ever loved.",
      label: "Shakespeare",
      order: 5,
    },
    {
      id: 6,
      user_id: 1,
      promptseq_id: 2,
      content: "The following are quotations from Samuel Johnson, one of history's greatest literary critics, on the art of poetry.",
      label: "Preamble",
      order: 1,
    },
    {
      id: 7,
      user_id: 1,
      promptseq_id: 2,
      content: "It is a general rule in poetry, that all appropriated terms of art should be sunk in general expressions, because poetry is to speak an universal language. This rule is still stronger with regard to arts not liberal, or confined to few, and therefore far removed from common knowledge.",
      label: "Terms of art",
      order: 2,
    },
    {
      id: 8,
      user_id: 1,
      promptseq_id: 2,
      content: "A long poem of mere sentiments becomes tedious; though all the parts are forcible, and every line kindles new rapture, the reader, if not relieved by the interposition of something that soothes the fancy, grows weary of admiration, and defers the rest.",
      label: "Mere sentiments",
      order: 3,
    },
    {
      id: 9,
      user_id: 1,
      promptseq_id: 2,
      content: "That verse may be melodious and pleasing, it is necessary, not only that the words be so ranged as that the accent may fall on its proper place, but that the syllables themselves be so chosen as to flow smoothly into one another. This is to be effected by a proportionate mixture of vowels and consonants, and by tempering the mute consonants with liquids and semivowels.",
      label: "Flow of syllables",
      order: 4,
    },
    {
      id: 10,
      user_id: 1,
      promptseq_id: 2,
      content: "The essence of verse is regularity, and its ornament is variety. To write verse is to dispose syllables and sounds harmonically by some known and settled rule -- a rule however lax enough to substitute similitude for identity, to admit change without breach of order, and to relieve the ear without disappointing it.",
      label: "Regularity and variety",
      order: 5,
    },
    {
      id: 11,
      user_id: 1,
      promptseq_id: 3,
      content: "Variable names are too often ambiguous. Developers fear verbosity too much. Variable names need not include unnecessary abbreviations. Variable naming schemes should not have inconsistent prefix and suffix standards, e.g. in one place 'user', in another 'userObj', and in a third 'userObject'.",
      label: "Readable naming",
      order: 1,
    },
    {
      id: 12,
      user_id: 1,
      promptseq_id: 3,
      content: "Functions which are too large normally do too many things, are harder to understand, are harder to test, and do not adequately respect separation of concerns. Functions should ideally be ten lines or shorter.",
      label: "Small functions",
      order: 2,
    },
    {
      id: 13,
      user_id: 1,
      promptseq_id: 3,
      content: "The ideal number of function arguments is zero. Do not write highly parameterised functions as they are harder to test.",
      label: "Few parameters",
      order: 3,
    },
    {
      id: 14,
      user_id: 1,
      promptseq_id: 4,
      content: "Don't forget that your code will have to be understood, tested, maintained, and understood by others. Write any code in such a way that is conducive to all of these processes.",
      label: "Lifecycle reminder",
      order: 1,
    },
    {
      id: 15,
      user_id: 1,
      promptseq_id: 5,
      content: "Pretend you are Oprah Winfrey, speaking to her audience on her show. You should introduce yourself, tell a story from your personal life, and then proceed onto your main topic for the episode.",
      label: "Oprah",
      order: 1,
    },
    {
      id: 16,
      user_id: 1,
      promptseq_id: 5,
      content: "Pretend you are performing stand-up. Tell three short jokes, at least one of which should finish with a pun for a punchline.",
      label: "Stand-up",
      order: 2,
    },
    {
      id: 17,
      user_id: 1,
      promptseq_id: 5,
      content: "Pretend you have to force the topic of space into your speech. You could mention space in the course of discussing the news, or telling a story, or telling a joke, or any other way you like.",
      label: "Space",
      order: 3,
    },
  ]);
};
